### PR TITLE
fix: header install catkin

### PR DESCRIPTION
**Pull request by reinzor**
Introduced by https://github.com/iris-ua/iris_lama/pull/14

### CODE REVIEW

**Comment by reinzor** [comment]
@facontidavide could you also review?

**Comment by facontidavide** [comment]
that is correct, my bad

**Comment by facontidavide** [comment]
@eupedrosa I think that finally you can release your packages to the community following the instructions here :)

http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease

**Comment by eupedrosa** [comment]
> @eupedrosa I think that finally you can release your packages to the community following the instructions here :)
>
>http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease

I think I will. Hopefully, soon.

**Pull request merged**
