### PR TITLE
[localization] add the option to trigger an update without motion

### PR DESCRIPTION
**Pull request by jcmonteiro**
### Why
Some users (like myself) might need this feature when migrating from AMCL.

### CODE REVIEW

**Comment by eupedrosa** [comment]
I'm trying to find another reason beyond the "AMCL also does it". Have you ever used this feature?

**Comment by jcmonteiro** [comment]
We currently make use of it in the company I work in. It makes a bigger difference in AMCL since calling the service multiple times will continuously update the current position. Nonetheless, the advantage for us comes when setting the robot's initial pose. Imagine you have a UI where the user is prompted to place the robot on the map. It is very useful to have a button to adjust the robot's position in said map instead of solely relying on the user's ability.

**Comment by jcmonteiro** [comment]
> What is the reasoning behind this feature for AMCL? AMCL has several mechanisms to handle errors.

It is debatable either someone should or should not use this feature in AMCL since it forces the localization towards a local minimum and might cause particle depletion if misused. In IRIS LaMa, however, I see no harm. A scan-match would be called anyway as soon as the robot moved above the configured thresholds.

**Comment by eupedrosa** [comment]
I can see it can be advantageous from the UI. Usually, after setting its initial pose, I move the robot to "snap it" into a better location.

>  It is very useful to have a button to adjust the robot's position in said map instead of solely relying on the user's ability.

Did you already test this workflow?

> It is debatable either someone should or should not use this feature in AMCL since it forces the localization towards a local minimum and might cause particle depletion if misused. 

That's my thought exactly.

Eitherway, it looks to be a simple change on this side o LaMa.

**Comment by jcmonteiro** [comment]
> I can see it can be advantageous from the UI. Usually, after setting its initial pose, I move the robot to "snap it" into a better location.

That's what I usually do. But it is usually harder to make a non-skilled user understand this behavior, so pressing a button is preferable.

> 
> > It is very useful to have a button to adjust the robot's position in said map instead of solely relying on the user's ability.
> 
> Did you already test this workflow?

Oh yes. We have been following this workflow for more than a year. Previously with AMCL and now with IRIS LaMa.

**Pull request merged**
